name: Update ClashX YAML

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0 点执行一次
  workflow_dispatch: # 支持手动触发

jobs:
  update-clashx:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 保证 GITHUB_TOKEN 可以推送
          fetch-depth: 0

      # 2. 设置 Node.js (如果抓节点需要用 JS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. 安装依赖（可选，根据你的抓取脚本）
      - name: Install dependencies
        run: npm install

      # 4. 抓取最新免费 ClashX 节点并生成 YAML
      - name: Generate ClashX YAML
        run: |
          node scripts/fetch-free-nodes.js > clashx/config.yaml
          echo "生成 YAML 完成"

      # 5. 配置 git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # 6. 提交并推送
      - name: Commit and push
        run: |
          git add clashx/config.yaml
          git commit -m "Update ClashX YAML with free proxies" || echo "No changes to commit"
          git push origin main
