name: Update ClashX YAML

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行一次
  workflow_dispatch:     # 手动触发

jobs:
  update-clashx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false # 使用自定义 token

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create fetchFreeProxies.js
        run: |
          mkdir -p clashx
          cat <<'EOF' > fetchFreeProxies.js
          import fs from 'fs';

          const outputPath = 'clashx/config.yaml';

          const freeNodes = [
            { name: 'Node1', type: 'socks5', server: '1.2.3.4', port: 1080 },
            { name: 'Node2', type: 'socks5', server: '5.6.7.8', port: 1080 }
          ];

          function generateYaml(nodes) {
            let yaml = 'proxies:\n';
            for (const n of nodes) {
              yaml += `  - name: ${n.name}\n`;
              yaml += `    type: ${n.type}\n`;
              yaml += `    server: ${n.server}\n`;
              yaml += `    port: ${n.port}\n`;
            }
            return yaml;
          }

          fs.mkdirSync('clashx', { recursive: true });
          fs.writeFileSync(outputPath, generateYaml(freeNodes), 'utf-8');
          console.log(`✅ YAML 已生成: ${outputPath}`);
          EOF

      - name: Generate ClashX YAML
        run: node fetchFreeProxies.js

      - name: Commit and push YAML
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add clashx/config.yaml
          git commit -m "Update ClashX YAML with free proxies [ci skip]" || echo "No changes to commit"
          git push https://${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main
