name: Update ClashX YAML

# 定时每天更新，也可自行修改 cron
on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点执行一次
  workflow_dispatch:       # 手动触发

jobs:
  update_yaml:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout 仓库（允许写权限）
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true   # 确保 GITHUB_TOKEN 可以 push

    # 2️⃣ 设置 Node.js（可选，如果你用 JS 脚本生成 YAML）
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3️⃣ 安装依赖（如果有）
    - name: Install dependencies
      run: npm install

    # 4️⃣ 生成 ClashX YAML
    - name: Generate ClashX YAML
      run: |
        mkdir -p clashx
        # 这里用 curl 示例抓取免费节点并生成 YAML
        # 你可以替换成你自己的抓取/处理脚本
        curl -s https://example.com/free-proxies.yaml > clashx/config.yaml
        echo "Generated clashx/config.yaml"

    # 5️⃣ 提交并 push 到 main
    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add clashx/config.yaml
        git commit -m "Update ClashX YAML with free proxies" || echo "No changes to commit"
        git push origin main
