name: Update ClashX YAML

# 定时执行（每天凌晨1点）
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  update-clashx-yaml:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. 安装依赖（如果有 package.json，可选）
      - name: Install dependencies
        run: |
          npm install

      # 4. 抓取免费节点并生成 YAML
      - name: Generate ClashX YAML
        run: |
          node fetchFreeProxies.js
          # 假设 fetchFreeProxies.js 输出到 clashx/config.yaml
          cat clashx/config.yaml

      # 5. 配置 Git 用户
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      # 6. 提交并推送到 main 分支（使用 PAT_TOKEN）
      - name: Commit and push YAML
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git add clashx/config.yaml
          git commit -m "Update ClashX YAML with free proxies [ci skip]" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
