name: Update ClashX Config

on:
  workflow_dispatch:  # 可以手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点执行

jobs:
  update-clashx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # 使用 PAT 推送

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install node-fetch@3 js-yaml@4

      - name: Fetch free proxies and generate YAML
        run: node fetchFreeProxies.js

      - name: Commit updated config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add clashx/config.yaml
          git commit -m "Update ClashX YAML with free proxies [ci skip]" || echo "No changes"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
