name: Update ClashX YAML

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-clashx:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # 2️⃣ 生成 YAML 文件
      - name: Generate ClashX YAML
        run: |
          mkdir -p clashx
          cat > clashx/config.yaml <<EOL
          # Minimal ClashX YAML example
          proxies:
            - name: "FreeProxy1"
              type: socks5
              server: 1.2.3.4
              port: 1080
            - name: "FreeProxy2"
              type: socks5
              server: 5.6.7.8
              port: 1080
          proxy-groups:
            - name: "Auto"
              type: select
              proxies:
                - FreeProxy1
                - FreeProxy2
          EOL

      # 3️⃣ 提交到 main
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add clashx/config.yaml
          git commit -m "Update ClashX YAML with free proxies [ci skip]" || echo "No changes to commit"
          git push origin main
